# Generated by Django 4.1.3 on 2022-11-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField(max_length=200)),
                ('stock', models.IntegerField()),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('fechaVenta', models.DateField(auto_now_add=True)),
                ('horaVenta', models.TimeField(auto_now_add=True)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagen', models.ImageField(upload_to='files/covers')),
            ],
        ),
    ]
